import type { Locale } from "@/lib/i18n";

export const childLabels: Record<Locale, Record<string, string>> = {
  "en-us": {
    "rag-pipelines": "RAG pipelines",
    "agentic-ai": "Agentic AI",
    "private-llms": "Private LLMs",
    "mern-polyglot": "MERN and polyglot stacks",
    "programmatic-seo": "Programmatic SEO",
    "mobile-applications": "Mobile applications",
    "product-design": "Product design",
    "digital-marketing": "Digital marketing",
  },
  "en-gb": {
    "rag-pipelines": "RAG pipelines",
    "agentic-ai": "Agentic AI",
    "private-llms": "Private LLMs",
    "mern-polyglot": "MERN and polyglot stacks",
    "programmatic-seo": "Programmatic SEO",
    "mobile-applications": "Mobile applications",
    "product-design": "Product design",
    "digital-marketing": "Digital marketing",
  },
  "en-lu": {
    "rag-pipelines": "RAG pipelines",
    "agentic-ai": "Agentic AI",
    "private-llms": "Private LLMs",
    "mern-polyglot": "MERN and polyglot stacks",
    "programmatic-seo": "Programmatic SEO",
    "mobile-applications": "Mobile applications",
    "product-design": "Product design",
    "digital-marketing": "Digital marketing",
  },
  "fr-lu": {
    "rag-pipelines": "Pipelines RAG",
    "agentic-ai": "IA agentique",
    "private-llms": "LLM privés",
    "mern-polyglot": "Stacks MERN et polyglottes",
    "programmatic-seo": "SEO programmatique",
    "mobile-applications": "Applications mobiles",
    "product-design": "Design produit",
    "digital-marketing": "Marketing numérique",
  },
  "en-in": {
    "rag-pipelines": "RAG pipelines",
    "agentic-ai": "Agentic AI",
    "private-llms": "Private LLMs",
    "mern-polyglot": "MERN and polyglot stacks",
    "programmatic-seo": "Programmatic SEO",
    "mobile-applications": "Mobile applications",
    "product-design": "Product design",
    "digital-marketing": "Digital marketing",
  },
};
